use zemoso;
CREATE TABLE Location
(LocNo VARCHAR(8) NOT NULL, 
 FacNo VARCHAR(8), 
 LocName VARCHAR(30) NOT NULL,
 CONSTRAINT PK_LOCATION PRIMARY KEY (LocNo),
 CONSTRAINT FK_FACNO FOREIGN KEY (FacNo) 
 REFERENCES FACILITY (FacNo) );
